<h1>Crear curso</h1>

<script>
 $(document).ready(function() {
    $('select').material_select();
  });
</script>
<?php

/** @var $form \Blog\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('goal')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('description')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('category_id')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>


