<?php $this->headLink()->appendStylesheet('/css/materialize.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/index.css'); ?>

<?php if (!empty($this->paginator)) : ?>
<div><p></p></div>
<div id="row"> 
    <div col s6 offset-s6>
            <a href="<?php echo $this->url('add');?>">Crear un curso</a>
    </div>
</div>            
    <div id="row">
        <?php foreach ($this->paginator as $course) : ?>
            <?php /** @var \Courses\Entity\Course $course */ ?>
            <?php $postedAt = $this->dateFormat(
                $course->getCreated(),
                IntlDateFormatter::MEDIUM, // Date
                IntlDateFormatter::MEDIUM, // Time
                'en_US'
            ); ?>

            <div class="card">
                <h2>
                    <span class="card-title"> <a href="<?php echo $this->url('display-course', array('categorySlug' => $course->getCategory()->getSlug(), 'courseSlug' => $course->getSlug())); ?>">
                        <?php echo $this->escapeHtml($course->getTitle()); ?>
                    </a>
                    </span>
                </h2>

                <div class="posted-at">
                    <?php //echo sprintf($this->translate('Posted on %s in the %s category.'), $postedAt, $this->escapeHtml($course->getCategory()->getName())); ?>

                    <?php if ($author = $course->getAuthor()) : ?>
                        <?php echo sprintf($this->translate('Written by %s'), $author->getFirstName() . ' ' . $author->getLastName()); ?>
                    <?php endif; ?>
                </div>

                <p class="excerpt">
                    <?php echo nl2br($this->escapeHtml($course->getContent())); ?>
                </p>
                
                <div class="card-action">
                Category:
                <a href="<?php echo $this->url('display-course', array('categorySlug' => $course->getCategory()->getSlug(), 'courseSlug' => $course->getSlug())); ?>">
                    <?php echo $this->translate($this->escapeHtml($course->getCategory()->getName())); ?>
                </a>
                
                <a href="<?php echo $this->url('display-course', array('categorySlug' => $course->getCategory()->getSlug(), 'courseSlug' => $course->getSlug())); ?>">
                    <?php echo $this->translate('Read more'); ?>
                </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="pagination-wrapper">
        <?php

        echo $this->paginationControl($this->paginator,
            'Sliding',
            'partial/pagination',
            array('route' => 'courses/paged'));

        ?>
    </div>

<?php else : ?>
    <p><?php echo $this->translate('There are currently no topics.'); ?></p>
<?php endif; ?>