<?php $this->headLink()->appendStylesheet('/css/blog/index/view-post.css'); ?>

<?php /** @var \Courses\Entity\Course $course */ ?>
<?php $course = $this->course; ?>

<?php $postedAt = $this->dateFormat(
    $course->getCreated(),
    IntlDateFormatter::MEDIUM, // Date
    IntlDateFormatter::MEDIUM, // Time
    'en_US'
); ?>

<div class="wrapper">
    <div class="blog-post">
        <h1><?php echo $this->escapeHtml($course->getTitle()); ?></h1>

        <div class="meta">
            <?php echo sprintf($this->translate('Posted on %s'), $postedAt); ?> |

            <?php if ($author = $course->getAuthor()) : ?>
                <?php echo sprintf($this->translate('Written by %s'), $author->getFirstName() . ' ' . $author->getLastName()); ?> |
            <?php endif; ?>
            <?php echo $this->escapeHtml($course->getCategory()->getName()); ?> |
            <a href="<?php echo $this->url('edit', array('courseId' => $course->getId())); ?>">edit</a> |
            <a href="<?php echo $this->url('delete', array('courseId' => $course->getId())); ?>">delete</a>
        </div>
        
        <p><?php echo nl2br($this->escapeHtml($course->getContent())); ?></p>
    </div>
</div>