<?php
$user = $this->member;
?>
<?php $memberAt = $this->dateFormat(
    $user->getCreated(),
    IntlDateFormatter::MEDIUM, // Date
    IntlDateFormatter::NONE, // Time
    'en_US'
); ?>


      <div class="row">
        <div class="col s12 m4">
          <div class="card-panel z-depth-1">
                <center><img class="circle responsive-img" onerror="this.src='<?php echo $this->basePath('img/profile/profile-pic.jpeg')?>';" src="<?php echo $this->basePath('img/profile/'.$user->getId().'.png')?>">
                <p class="card-title"><?php echo sprintf($user->getFirstName().' '.$user->getLastName());?></p>
            </center><div class="card-content">
                <ul class="collapsible z-depth-0" data-collapsible="accordion">
                    <li>
                        <div class="collapsible-header"><?php echo sprintf('Más sobre mi'); ?></div>
                        <div class="collapsible-body">
                            <?php echo sprintf($user->getBio()); ?>
                            <?php echo sprintf('Edad');?>
                            <?php echo sprintf($user->getAge()); ?>
                            <?php echo sprintf('Miembro desde:'); ?>
                            <?php echo sprintf($memberAt); ?>
                        </div>

                    </li>
                    <li>
                         <div class="collapsible-header"><?php echo sprintf('Contacto'); ?></div>
                         <div class="collapsible-body">
                             <?php echo sprintf('Correo electrónico'); ?>
                            <?php echo sprintf($user->getEmail()); ?>
                         </div>
                    </li>
                   
                </ul>         
                <ul>
                    <li><a href="<?php echo $this->url('edit-info',array('nickname' => $user->getNickname()))?>">Editar información básica</a></li>
                    <li><a href="<?php echo $this->url('add-job')?>">Agregar trabajo</a></li>
                    <li><a href="<?php echo $this->url('avatar')?>">Agregar avatar</a></li>
                </ul>
            </div>
          </div>
        </div>
        <div class="col s12 m8">
            <div class="card-panel">
                <div class="card-title">
                    <ul class="tabs">
                        <li class="tab col s3"><a  href="">Educación</a></li>
                        <li class="tab col s3"><a  href="#career">Experiencia laboral</a></li> 
                        <li class="tab col s3"><a  href="">Cursos</a></li>
                        <li class="tab col s3"><a  href="">Proyectos</a></li> 
                        
                    </ul>
                </div>
                <div class=card-content">
                    <div id="career">
                        <table class="responsive-table centered">
                        <thead>
                            <tr>
                                <th width="20%">Organizacion</th>
                                <th width="20%">Puesto</th>
                                <th width="50%">Descripcion del puesto</th>
                                <th width="*">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php
                           foreach($this->career as $career){ 
                               ?>  
                            <tr>
                                <td> <?php  echo sprintf($career['organization']); ?> </td>
                                <td> <?php  echo sprintf($career['position']); ?> </td>
                                <td> <?php  echo sprintf($career['job_description']); ?> </td>
                                <td> <a href="<?php echo $this->url('edit-job',array('jobId' => $career['id']))?>">Editar</a></td>
                            </tr>

                            <?php }?>
                        </tbody>
                    </table>
                    
                    </div>
              </div>
            </div>
        </div>
     